# Ejercicio día 8
**Programación I**

In [134]:
import numpy as np

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [92]:
f=10
col=10
ceros=np.zeros(f*col)
m=np.arange(100)

In [93]:
matriz=np.random.choice(m, int((10*10)/2), replace=False)
ceros[matriz]=1
ceros.resize((10,10))
ceros

array([[0., 0., 1., 1., 0., 1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 0., 1.],
       [0., 1., 0., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 1., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 1.],
       [0., 0., 0., 1., 1., 0., 1., 0., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 

In [94]:
ceros=np.zeros([5,2])
ceros.resize((10,1))
ceros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [95]:
unos=np.ones([5,2])
unos.resize((10,1))
unos

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

2.	Apile ambos vectores a lo largo de una tercera dimensión.

In [96]:
np.dstack((ceros,unos))

array([[[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]]])

3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente.

In [97]:
unos.resize((1,10))
unos

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
ceros.resize((1,10))
ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [110]:
(np.concatenate((ceros,unos))).reshape((20,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 


In [7]:
n=10
var = np.random.randint(10, size=(n, 3))
var

array([[5, 0, 5],
       [2, 0, 4],
       [5, 1, 8],
       [2, 6, 1],
       [3, 4, 3],
       [9, 8, 4],
       [5, 7, 6],
       [4, 7, 0],
       [5, 3, 8],
       [9, 6, 6]])

2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [107]:
def f(x):
    
    return (2*var[0:n,0]+3*var[0:n,1]+var[0:n,2]**2).reshape((n,1))


In [108]:
f(var)

array([[35],
       [20],
       [77],
       [23],
       [27],
       [58],
       [67],
       [29],
       [83],
       [72]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

Caso: Cuadrado menor en una esquina

In [139]:
sqr50=np.random.randint(0,2,size=(50,50))
sqr20=sqr50[30:,0:20]
print (50*50*sum(sum(sqr20))/sum(sum(sqr50)))

408.4451460142068


Caso: Cuadrados Concentricos

In [138]:
sqr50=np.random.randint(0,2,size=(50,50))
sqr20=sqr50[15:35,15:35]
print (50*50*sum(sum(sqr20))/sum(sum(sqr50)))

416.331456154465


2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)

Archivos NPY

In [113]:
arr = np.random.randint(10, size=(5, 5))
arr

array([[8, 0, 9, 9, 1],
       [9, 2, 4, 9, 0],
       [5, 9, 6, 7, 5],
       [5, 2, 3, 7, 9],
       [6, 6, 2, 5, 9]])

In [114]:
np.save("archivo_npy.npy",arr)

In [115]:
np.load("archivo_npy.npy")

array([[8, 0, 9, 9, 1],
       [9, 2, 4, 9, 0],
       [5, 9, 6, 7, 5],
       [5, 2, 3, 7, 9],
       [6, 6, 2, 5, 9]])

Archivos NPZ

In [124]:
np.savez("archivo_npz.npz",arr)

In [131]:
np.load("archivo_npz.npz")

In [132]:
file_npz=np.load("archivo_npz.npz")
file_npz.files

['arr_0']

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    

In [111]:
##Con esta funcion guarda los arreglos de un archivo de texto
x=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int32)
np.savetxt("prueba.txt",x)

In [112]:
#Con esta funcion carga los arreglos de un archivo de texto
np.loadtxt("prueba.txt")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [35]:
n=10
variables = np.random.randint(100, size=(n, 7))
variables


array([[23, 76, 83, 75, 12, 79, 60],
       [91, 85, 33, 97, 52, 85, 84],
       [73, 31, 12, 55, 78, 69, 73],
       [33,  3, 62, 32, 11, 72, 98],
       [45, 73, 71, 34, 41, 82, 15],
       [ 9, 20,  2, 19, 74, 33, 19],
       [ 2, 53, 58, 82, 11, 76, 76],
       [75, 75, 49, 97, 98, 23, 78],
       [91, 82,  2, 16, 85, 24, 13],
       [33, 42,  9, 24, 90, 50, 66]])

In [42]:
np.savetxt("estimacionMCO.csv", variables, delimiter=' ', fmt='%d')

In [26]:
def estimacionMCO(datos):
    return np.loadtxt("estimacionMCO.csv", delimiter=',', skiprows=1)

In [28]:
datos=1
estimacionMCO(datos)

array([[0.97748995, 0.18917939, 0.20513222, 0.31936232, 0.29773124,
        0.69318276, 0.30423391],
       [0.12539001, 0.26668247, 0.17440796, 0.79643397, 0.79142584,
        0.56020648, 0.49705229],
       [0.17081097, 0.73571549, 0.4749512 , 0.75607613, 0.98845527,
        0.37152488, 0.14639633],
       [0.71468347, 0.77195859, 0.3785725 , 0.59741828, 0.26881934,
        0.3647765 , 0.90220233],
       [0.06518178, 0.87919118, 0.60466537, 0.33905272, 0.71405363,
        0.84851003, 0.09751689],
       [0.19063337, 0.45771046, 0.2428601 , 0.95816729, 0.87867416,
        0.21305151, 0.44228944],
       [0.55838379, 0.98403945, 0.92940718, 0.37420553, 0.942753  ,
        0.85620295, 0.86205779],
       [0.52553142, 0.33674251, 0.74307742, 0.81600889, 0.70066451,
        0.93926452, 0.65115339],
       [0.49355334, 0.02030058, 0.51231172, 0.41579386, 0.97848751,
        0.37150138, 0.31189439],
       [0.49088189, 0.01141994, 0.26502864, 0.27138117, 0.19882864,
        0.73271098, 0.4